allow_unicode: true
canonical: false
default_flow_style: false
default_style: null
encoding: utf-8
explicit_end: null
explicit_start: null
indent: 2
line_break: null
tags: null
version: null
width: null